<?php

/**
 * @file
 * Something about the file
 */


/**
 * Hooks
 */

/**
 * Implements hook_bean_types_api_info().
 */
function featuredbean_bean_types_api_info() {
  return array(
    'api' => bean_current_version(),
  );
}

/**
 * Implements hook_bean_types().
 */
function featuredbean_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'featuredbean');

  $plugins['featuredbean'] = array(
    'label' => t('Featured Content'),
    'handler' => array(
      'class' => 'Featuredbean',
      'parent' => 'BeanPlugin',
      'path' => $plugin_path,
      'file' => 'FeaturedBean.class.php',
    ),
    'editable' => TRUE,
  );

  return $plugins;
}
