<?php
/**
 * @file
 * ombubeans.features.field.inc
 */

/**
 * Implements hook_field_default_fields().
 */
/* function ombubeans_field_default_fields() { */
/*   $fields = array(); */

/*   // Exported field: 'bean-ombubeans_sociallinks-field_ombubeans_sociallinks' */
/*   $fields['bean-ombubeans_sociallinks-field_ombubeans_sociallinks'] = array( */
/*     'field_config' => array( */
/*       'active' => '1', */
/*       'cardinality' => '-1', */
/*       'deleted' => '0', */
/*       'entity_types' => array(), */
/*       'field_name' => 'field_ombubeans_sociallinks', */
/*       'foreign keys' => array(), */
/*       'indexes' => array(), */
/*       'module' => 'field_sociallinks', */
/*       'settings' => array(), */
/*       'translatable' => '0', */
/*       'type' => 'sociallinks', */
/*     ), */
/*     'field_instance' => array( */
/*       'bundle' => 'ombubeans_sociallinks', */
/*       'default_value' => NULL, */
/*       'deleted' => '0', */
/*       'description' => '', */
/*       'display' => array( */
/*         'default' => array( */
/*           'label' => 'hidden', */
/*           'module' => 'field_sociallinks', */
/*           'settings' => array(), */
/*           'type' => 'sociallinks_sociallinks_formatter', */
/*           'weight' => '0', */
/*         ), */
/*       ), */
/*       'entity_type' => 'bean', */
/*       'field_name' => 'field_ombubeans_sociallinks', */
/*       'label' => 'Social Links', */
/*       'required' => 0, */
/*       'settings' => array( */
/*         'user_register_form' => FALSE, */
/*       ), */
/*       'widget' => array( */
/*         'active' => 0, */
/*         'module' => 'field_sociallinks', */
/*         'settings' => array(), */
/*         'type' => 'sociallinks_sociallinks_widget', */
/*         'weight' => '1', */
/*       ), */
/*     ), */
/*   ); */

/*   // Translatables */
/*   // Included for use with string extractors like potx. */
/*   t('Social Links'); */

/*   return $fields; */
/* } */
