<?php

/**
 * @file
 * Media Bean.
 *
 * A basic bean that provides a simple interface for embedding media content in
 * a bean.
 */

/**
 * Implements hook_menu().
 */
function bean_media_menu() {
  $items = array();

  $items['media-bean-options'] = array(
    'page callback' => 'bean_media_ajax_options',
    'access arguments' => array('create an bean_media bean'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_bean_types_api_info().
 */
function bean_media_bean_types_api_info() {
  return array(
    'api' => bean_current_version(),
  );
}

/**
 * Implements hook_bean_types().
 */
function bean_media_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'bean_media') . '/plugins';

  $plugins['bean_media'] = array(
    'label' => t('Media'),
    'handler' => array(
      'class' => 'MediaBean',
      'parent' => 'BeanPlugin',
    ),
    'path' => $plugin_path,
    'file' => 'MediaBean.class.php',
    'editable' => TRUE,
  );

  return $plugins;
}
