<?php
/**
 * @file
 * Callout bean tile.
 */

/**
 * Implements hook_bean_types_api_info().
 */
function bean_callout_bean_types_api_info() {
  return array(
    'api' => bean_current_version(),
  );
}

/**
 * Implements hook_bean_types().
 */
function bean_callout_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'bean_callout');

  $plugins['bean_callout'] = array(
    'label' => t('Callout'),
    'handler' => array(
      'class' => 'BeanCallout',
      'parent' => 'BeanPlugin',
      'path' => $plugin_path . '/plugins',
      'file' => 'BeanCallout.class.php',
    ),
    'editable' => TRUE,
  );

  return $plugins;
}

/**
 * Implements hook_bean_style_info().
 */
function bean_callout_bean_style_info() {
  return array(
    'basic' => array(
      'label' => 'Basic',
      'class' => 'BeanStyleBasic',
      'bean_types' => array(
        'bean_callout',
      ),
    ),
    'basic_carousel' => array(
      'label' => 'Callout Carousel',
      'class' => 'BeanStyleBasicCarousel',
      'bean_types' => array(
        'bean_callout',
      ),
    ),
  );
}

/**
 * Implements hook_bean_style_options_alter().
 */
function bean_callout_bean_style_options_alter(&$options, $context) {
  if ($context['bundle'] == 'bean_callout') {
    unset($options['']);
    unset($options['basic_carousel']);
  }
}
