<?php
/**
 * @file
 * A Bean with just a rich-text field
 */

include_once 'bean_rte.features.inc';

/**
 * Implements hook_bean_types_api_info().
 */
function bean_rte_bean_types_api_info() {
  return array(
    'api' => bean_current_version(),
  );
}

/**
 * Implements hook_bean_types().
 */
function bean_rte_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'bean_rte') . '/plugins';

  $plugins['bean_rte_rte'] = array(
    'label' => t('Rich text'),
    'handler' => array(
      'class' => 'RteBean',
      'parent' => 'BeanPlugin',
    ),
    'path' => $plugin_path,
    'file' => 'RteBean.class.php',
    'editable' => TRUE,
  );

  return $plugins;
}
