<?php

/**
 * @file
 * Embed (iFrame) bean.
 */

/**
 * Implements hook_bean_types_api_info().
 */
function bean_embed_bean_types_api_info() {
  return array(
    'api' => bean_current_version(),
  );
}

/**
 * Implements hook_bean_types().
 */
function bean_embed_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'bean_embed') . '/plugins';

  $plugins['bean_embed'] = array(
    'label' => t('Embed'),
    'handler' => array(
      'class' => 'EmbedBean',
      'parent' => 'BeanPlugin',
    ),
    'path' => $plugin_path,
    'file' => 'EmbedBean.class.php',
    'editable' => TRUE,
  );

  return $plugins;
}

/**
 * Implements hook_bean_style_info().
 */
function bean_embed_bean_style_info() {
  return array(
    'bean_embed_style'  => array(
      'label' => 'URL',
      'class' => 'BeanStyleIframe',
      'bean_types' => array(
        'bean_embed',
      ),
      'file' => 'BeanStyleIframe.php',
    ),
  );
}

/**
 * Implements hook_bean_style_options().
 */
function bean_embed_bean_style_options(&$options, $context) {
  // Remove default style for bean_embed styles.
  if ($context['bean']->type == 'bean_embed') {
    unset($options['']);
  }
}
