<?php

/**
 * @file
 * Something about the file
 */


/**
 * Hooks
 */

/**
 * Implements hook_bean_types_api_info().
 */
function linkbean_bean_types_api_info() {
  return array(
    'api' => bean_current_version(),
  );
}

/**
 * Implements hook_bean_types().
 */
function linkbean_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'linkbean');

  $plugins['linkbean'] = array(
    'label' => t('Links'),
    'handler' => array(
      'class' => 'LinkBean',
      'parent' => 'BeanPlugin',
      'path' => $plugin_path,
      'file' => 'LinkBean.class.php',
    ),
    'editable' => TRUE,
  );

  return $plugins;
}

/**
 * Implements hook_bean_style_info().
 */
function linkbean_bean_style_info() {
  return array(
    'linkbean_style'  => array(
      'label' => 'Default',
      'class' => 'LinkBeanStyle',
      'bean_types' => array(
        'linkbean',
      ),
    ),
  );
}

/**
 * Implements hook_bean_style_options().
 */
function linkbean_bean_style_options(&$options, $context) {
  // Remove default style for linkbean styles.
  if ($context['bean']->type == 'linkbean') {
    unset($options['']);
  }
}
