<?php

/**
 * @file
 * Bean Feed module.
 */

/**
 * Implements hook_bean_types_api_info().
 */
function bean_feed_bean_types_api_info() {
  return array(
    'api' => bean_current_version(),
  );
}

/**
 * Implements hook_bean_types().
 */
function bean_feed_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'bean_feed');

  $plugins['bean_feed'] = array(
    'label' => t('Feed'),
    'handler' => array(
      'class' => 'BeanFeed',
      'parent' => 'BeanPlugin',
      'path' => $plugin_path . '/includes',
      'file' => 'BeanFeed.php',
    ),
    'editable' => TRUE,
  );

  return $plugins;
}

/**
 * Implements hook_theme().
 */
function bean_feed_theme($existing, $type, $theme, $path) {
  return array(
    'bean_feed_item' => array(
      'variables' => array('bean' => NULL, 'link' => NULL, 'title' => NULL, 'description' => NULL, 'date' => NULL),
      'template' => 'bean-feed-item',
    ),
  );
}

/**
 * AJAX callback for bean form.
 */
function bean_feed_ajax_callback($form, $form_state) {
  return $form['feeds'];
}

/**
 * Select form for selecting multiple feeds.
 */
function bean_feed_select_form($form, $form_state, $bean) {
  if (count($bean->feeds) > 1) {
    $form['#bean'] = $bean;

    $options = array();
    foreach ($bean->feeds as $feed) {
      $options[$feed['url']] = $feed['title'];
    }

    $form['feeds'] = array(
      '#type' => 'select',
      '#options' => $options,
      '#ajax' => array(
        'callback' => 'bean_feed_select_callback',
        'wrapper' => 'bean-feed-wrapper-' . $bean->bid,
      ),
    );
  }

  return $form;
}

/**
 * AJAX callback for feed select form.
 */
function bean_feed_select_callback($form, $form_state) {
  $content = array();

  $items = BeanFeed::getFeedItems($form['#bean'], $form_state['values']['feeds']);
  if ($items) {
    $rendered_items = array();
    foreach ($items as $item) {
      $rendered_items[] = theme('bean_feed_item', $item);
    }

    $content['items'] = array(
      '#theme' => 'item_list',
      '#items' => $rendered_items,
      '#attributes' => array(
        'id' => 'bean-feed-wrapper-' . $form['#bean']->bid,
      ),
    );
  }

  return $content;
}
