<?php

/**
 * @file
 * Menu block bean.
 */

/**
 * Implements hook_bean_types_api_info().
 */
function bean_menu_block_bean_types_api_info() {
  return array(
    'api' => bean_current_version(),
  );
}

/**
 * Implements hook_bean_types().
 */
function bean_menu_block_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'bean_menu_block') . '/plugins';

  $plugins['bean_menu_block'] = array(
    'label' => t('Menu block'),
    'handler' => array(
      'class' => 'MenuBlockBean',
      'parent' => 'BeanPlugin',
    ),
    'path' => $plugin_path,
    'file' => 'MenuBlockBean.class.php',
  );

  return $plugins;
}
