<?php

/**
 * @file
 * Menu block bean.
 */

/**
 * Implements hook_bean_types_api_info().
 */
function bean_menu_block_bean_types_api_info() {
  return array(
    'api' => bean_current_version(),
  );
}

/**
 * Implements hook_bean_types().
 */
function bean_menu_block_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'bean_menu_block') . '/plugins';

  $plugins['bean_menu_block'] = array(
    'label' => t('Menu'),
    'handler' => array(
      'class' => 'MenuBlockBean',
      'parent' => 'BeanPlugin',
    ),
    'path' => $plugin_path,
    'file' => 'MenuBlockBean.class.php',
    'editable' => TRUE,
  );

  return $plugins;
}

/**
 * Implements hook_bean_style_info().
 */
function bean_menu_block_bean_style_info() {
  return array(
    'bean_menu_style'  => array(
      'label' => 'Default',
      'class' => 'MenuBlockBeanStyle',
      'bean_types' => array(
        'bean_menu_block',
      ),
    ),
  );
}

/**
 * Implements hook_bean_style_options().
 */
function bean_menu_block_bean_style_options(&$options, $context) {
  // Remove default style for bean_link styles.
  if ($context['bean']->type == 'bean_menu_block') {
    unset($options['']);
  }
}
